"""Generic backward liveness analysis for IR and machine CFGs.

The analysis is deliberately independent from register allocation.  A caller
supplies a :class:`UseDefProvider` that knows how to read a concrete
instruction representation.  The solver then computes block-level and
instruction-level live sets over the unified CFG.

Data-flow equations
-------------------
Without Phi nodes::

    live_out[B] = union(live_in[S] for S in successors(B))
    live_in[B]  = uses[B] | (live_out[B] - defs[B])

With Phi nodes, values used by a Phi must travel only along the corresponding
predecessor edge::

    edge_live[B, S] = (live_in[S] - phi_defs[S]) | phi_uses[B, S]
    live_out[B]     = union(edge_live[B, S] for S in successors(B))
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import AbstractSet, Any, Mapping, Optional, Protocol

from scratchv.analysis.cfg import (
    BlockId,
    ControlFlowGraph,
    InstructionId,
    ValueId,
)


# ---------------------------------------------------------------------------
# Public result types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BlockLiveness:
    """Block-level use/def and live-in/live-out sets."""

    uses: frozenset[ValueId]
    defs: frozenset[ValueId]
    live_in: frozenset[ValueId]
    live_out: frozenset[ValueId]


@dataclass(frozen=True)
class LivenessResult:
    """Complete liveness answer for one CFG.

    ``blocks`` is keyed by ``BlockId`` (block name in ScratchV's current CFG).
    ``edge_live`` contains values live across a specific predecessor/successor
    edge, which is what Phi-aware rewriting and spill placement need.
    ``live_before``/``live_after`` are keyed by ``InstructionId`` generated by
    :func:`scratchv.analysis.cfg.build_cfg`.
    """

    blocks: Mapping[BlockId, BlockLiveness]
    edge_live: Mapping[
        tuple[BlockId, BlockId],
        frozenset[ValueId],
    ]
    live_before: Mapping[InstructionId, frozenset[ValueId]]
    live_after: Mapping[InstructionId, frozenset[ValueId]]


# ---------------------------------------------------------------------------
# Provider protocol
# ---------------------------------------------------------------------------

class UseDefProvider(Protocol):
    """Concrete-instruction semantics needed by liveness.

    ``uses``/``defs`` return value identifiers for one instruction.
    ``edge_uses`` returns Phi operands that are only read on the given CFG
    edge.  ``phi_defs`` returns values defined by Phi nodes at a block's entry.
    """

    def uses(self, instr: Any) -> AbstractSet[ValueId]: ...

    def defs(self, instr: Any) -> AbstractSet[ValueId]: ...

    def edge_uses(
        self,
        pred: BlockId,
        succ: BlockId,
    ) -> AbstractSet[ValueId]: ...

    def phi_defs(self, block: BlockId) -> AbstractSet[ValueId]: ...


# ---------------------------------------------------------------------------
# Block-level transfer summary
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class _BlockSummary:
    uses: frozenset[ValueId]
    defs: frozenset[ValueId]


def _summarize_block(
    cfg: ControlFlowGraph,
    block_id: BlockId,
    provider: UseDefProvider,
) -> _BlockSummary:
    node = cfg.nodes.get(block_id)
    if node is None:
        return _BlockSummary(frozenset(), frozenset())

    if isinstance(node.instructions, int):
        instructions = []
    else:
        instructions = list(node.instructions)

    block_defs: set[ValueId] = set()
    block_uses: set[ValueId] = set()

    for instr in instructions:
        instr_uses = set(provider.uses(instr))
        instr_defs = set(provider.defs(instr))

        # Values read before their first definition in this block are live-in
        # uses.  Values read and written by the same instruction are treated
        # as used before defined.
        block_uses.update(instr_uses - block_defs)
        block_defs.update(instr_defs)

    return _BlockSummary(
        uses=frozenset(block_uses),
        defs=frozenset(block_defs),
    )


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

def analyze_liveness(
    cfg: ControlFlowGraph,
    provider: UseDefProvider,
) -> LivenessResult:
    """Compute live sets for every block, CFG edge, and instruction.

    The solver is a reverse worklist iteration and converges to the least
    fixed point of the standard data-flow equations.
    """

    block_ids = list(cfg.nodes)
    summaries = {
        block_id: _summarize_block(cfg, block_id, provider)
        for block_id in block_ids
    }

    live_in: dict[BlockId, frozenset[ValueId]] = {
        block_id: frozenset() for block_id in block_ids
    }
    live_out: dict[BlockId, frozenset[ValueId]] = {
        block_id: frozenset() for block_id in block_ids
    }

    worklist = deque(block_ids)
    in_worklist = set(block_ids)

    while worklist:
        block_id = worklist.popleft()
        in_worklist.discard(block_id)

        successors = sorted(cfg.successors(block_id))
        if not successors:
            new_out = frozenset()
        else:
            out_parts: list[frozenset[ValueId]] = []
            for succ in successors:
                phi_defs = frozenset(provider.phi_defs(succ))
                edge_uses = frozenset(provider.edge_uses(block_id, succ))
                out_parts.append(
                    (live_in[succ] - phi_defs) | edge_uses
                )
            new_out = frozenset().union(*out_parts) if out_parts else frozenset()

        summary = summaries[block_id]
        new_in = summary.uses | (new_out - summary.defs)

        if new_in != live_in[block_id] or new_out != live_out[block_id]:
            live_in[block_id] = new_in
            live_out[block_id] = new_out
            for pred in sorted(cfg.predecessors(block_id)):
                if pred not in in_worklist:
                    worklist.append(pred)
                    in_worklist.add(pred)

    # Compute Phi-aware edge live sets after the fixed point has stabilised.
    edge_live: dict[
        tuple[BlockId, BlockId],
        frozenset[ValueId],
    ] = {}
    for edge in cfg.edges:
        pred, succ = edge.source, edge.target
        if succ not in live_in:
            continue
        edge_live[(pred, succ)] = (
            live_in[succ] - frozenset(provider.phi_defs(succ))
        ) | frozenset(provider.edge_uses(pred, succ))

    # Instruction-level live_after/live_before from each block's live_out.
    live_before: dict[InstructionId, frozenset[ValueId]] = {}
    live_after: dict[InstructionId, frozenset[ValueId]] = {}

    for block_id, node in cfg.nodes.items():
        if isinstance(node.instructions, int):
            instructions = []
        else:
            instructions = list(node.instructions)

        instruction_ids = node.instruction_ids
        if len(instruction_ids) != len(instructions):
            # A manually constructed CFG may not carry instruction ids.
            # Generate stable ids on demand for those callers.
            instruction_ids = [
                f"{block_id}:{index}"
                for index in range(len(instructions))
            ]

        live = set(live_out[block_id])
        for index in reversed(range(len(instructions))):
            instr = instructions[index]
            instr_id = instruction_ids[index]

            defs = set(provider.defs(instr))
            uses = set(provider.uses(instr))

            live_after[instr_id] = frozenset(live)
            live = (live - defs) | uses
            live_before[instr_id] = frozenset(live)

    blocks = {
        block_id: BlockLiveness(
            uses=summaries[block_id].uses,
            defs=summaries[block_id].defs,
            live_in=live_in[block_id],
            live_out=live_out[block_id],
        )
        for block_id in block_ids
    }

    return LivenessResult(
        blocks=blocks,
        edge_live=edge_live,
        live_before=live_before,
        live_after=live_after,
    )


__all__ = [
    "BlockLiveness",
    "LivenessResult",
    "UseDefProvider",
    "analyze_liveness",
]