; LLVM IR generated by ScratchV
; ModuleID = "scratchv_module"
target triple = "riscv64-unknown-elf"

declare float @expf(float) nounwind readonly
declare float @tanhf(float) nounwind readonly
declare double @exp(double) nounwind readonly
declare double @tanh(double) nounwind readonly
declare void @print_f32(float) nounwind

define float @add_graph(float %A, float %B) {
; --- entry ---
    %v_1_1 = fadd float %A, %B
    ret float %v_1_1
}
