#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
ONNX to ScratchV DSL Standalone Converter
-----------------------------------------
Convert ONNX model files (.onnx) to ScratchV DSL text format (.dsl).

This is a standalone script that does not depend on the full ScratchV
compiler pipeline, only on the onnx and numpy libraries.

Usage:
    python onnx_to_dsl_standalone.py model.onnx -o model.dsl
    python onnx_to_dsl_standalone.py model.onnx --inline-weights -o model.dsl
"""

import argparse
import sys
import os

import onnx
import numpy as np
from onnx import AttributeProto


def format_attribute_value(attr):
    """
    Convert ONNX attribute to a DSL-friendly string representation.
    Returns a tuple (type_name, value_str) or (None, None) if unsupported.
    """
    if attr.type == AttributeProto.UNDEFINED:
        return None, None
    elif attr.type == AttributeProto.FLOAT:
        return "float", str(attr.f)
    elif attr.type == AttributeProto.INT:
        return "int", str(attr.i)
    elif attr.type == AttributeProto.STRING:
        return "string", f'"{attr.s.decode()}"'
    elif attr.type == AttributeProto.FLOATS:
        return "floats", "[" + ", ".join(str(v) for v in attr.floats) + "]"
    elif attr.type == AttributeProto.INTS:
        return "ints", "[" + ", ".join(str(v) for v in attr.ints) + "]"
    elif attr.type == AttributeProto.STRINGS:
        return "strings", "[" + ", ".join(f'"{s.decode()}"' for s in attr.strings) + "]"
    elif attr.type == AttributeProto.TENSOR:
        # 不展开具体数值，只保留形状信息，防止文件过大
        return "tensor", f"shape={list(attr.t.dims)}, dtype={attr.t.data_type}"
    elif attr.type == AttributeProto.GRAPH:
        return "graph", "<subgraph>"
    else:
        return f"attr_{attr.name}", "<unsupported>"


def convert_onnx_to_dsl(onnx_path, dsl_path, inline_weights=False):
    """
    Core conversion routine.
    Loads an ONNX model, traverses its graph, and writes a .dsl file.
    """
    if not os.path.exists(onnx_path):
        print(f"[ERROR] ONNX file not found: {onnx_path}")
        sys.exit(1)

    try:
        model = onnx.load(onnx_path)
        graph = model.graph
    except Exception as e:
        print(f"[ERROR] Failed to load ONNX model: {e}")
        sys.exit(1)

    initializers = {init.name: init for init in graph.initializer}

    # 区分真实输入和权重常量
    real_inputs = []
    for inp in graph.input:
        if inp.name not in initializers:
            real_inputs.append(inp)

    try:
        with open(dsl_path, "w", encoding="utf-8") as f:
            # ----- Header -----
            f.write(f"# Generated by onnx_to_dsl_standalone.py from: {os.path.basename(onnx_path)}\n")
            f.write("# DSL format for ScratchV compiler.\n\n")

            # ----- Inputs -----
            f.write("# Model inputs (data to be provided at inference time)\n")
            for inp in real_inputs:
                shape_str = "?"
                try:
                    dims = []
                    for d in inp.type.tensor_type.shape.dim:
                        if d.dim_value != 0:
                            dims.append(str(d.dim_value))
                        else:
                            dims.append("?")
                    shape_str = f"shape=[{', '.join(dims)}]"
                except Exception:
                    pass
                f.write(f"# input: {inp.name} {shape_str}\n")
                f.write(f"{inp.name} = input()\n")
            if real_inputs:
                f.write("\n")

            # ----- Weights (Initializers) -----
            if initializers:
                f.write("# Model weights / constants (initializers from ONNX)\n")
                for name, init in initializers.items():
                    if inline_weights:
                        arr = onnx.numpy_helper.to_array(init)
                        if arr.size <= 32:  # 只内联小张量，防止DSL过于庞大
                            flat = arr.flatten().tolist()
                            f.write(f"{name} = {flat}  # shape={list(arr.shape)}, dtype={arr.dtype}\n")
                            continue
                    f.write(f"# {name} = load_weight(...)  # shape={list(init.dims)}, dtype={init.data_type}\n")
                f.write("\n")

            # ----- Graph Nodes -----
            f.write("# Computation graph nodes\n")
            for idx, node in enumerate(graph.node):
                op_type = node.op_type
                dsl_op = op_type.lower()

                # Parse attributes
                attr_kwargs = []
                for attr in node.attribute:
                    type_name, val_str = format_attribute_value(attr)
                    if type_name in ["float", "int", "string", "floats", "ints", "strings"]:
                        attr_kwargs.append(f"{attr.name}={val_str}")
                    else:
                        # 复杂属性（如张量、子图）暂时注释保留
                        f.write(f"# Complex attribute {attr.name}: {type_name} = {val_str}\n")

                # Assemble DSL line
                out_str = ", ".join(node.output) if len(node.output) > 1 else node.output[0]
                in_str = ", ".join(node.input) if node.input else ""

                if attr_kwargs:
                    line = f"{out_str} = {dsl_op}({in_str}, {', '.join(attr_kwargs)})"
                else:
                    line = f"{out_str} = {dsl_op}({in_str})"

                f.write(f"{line}  # node {idx}: {op_type}\n")

            # ----- Return -----
            f.write("\n# Return outputs\n")
            if len(graph.output) > 1:
                ret_str = ", ".join(out.name for out in graph.output)
            else:
                ret_str = graph.output[0].name
            f.write(f"return {ret_str}\n")

        print(f"[INFO] Successfully converted ONNX to DSL: {dsl_path}")
        print(f"[INFO]   Inputs: {len(real_inputs)}, Weights: {len(initializers)}, Operators: {len(graph.node)}")

    except IOError as e:
        print(f"[ERROR] Cannot write to output file {dsl_path}: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"[ERROR] Unexpected error during conversion: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Convert ONNX model to ScratchV DSL text format.",
        epilog="Example: python onnx_to_dsl_standalone.py model.onnx -o model.dsl"
    )
    parser.add_argument(
        "onnx_file",
        help="Path to the input .onnx file"
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Path to the output .dsl file (default: same basename as input with .dsl)"
    )
    parser.add_argument(
        "--inline-weights",
        action="store_true",
        help="Inline small weight tensors (<=32 elements) directly into the DSL file for debugging"
    )

    args = parser.parse_args()

    if args.output is None:
        base = os.path.splitext(args.onnx_file)[0]
        args.output = base + ".dsl"

    convert_onnx_to_dsl(args.onnx_file, args.output, args.inline_weights)


if __name__ == "__main__":
    main()