"""LLVM IR codegen: translates ScratchV IR to LLVM IR text format.

Produces human-readable .ll files suitable for ``llc``, ``opt``, or ``lli``.
No external dependencies beyond Python — the output is standard LLVM IR.

The generator is single-pass and memory-based: control flow uses
``alloca``/``load``/``store`` plus explicit branches, and every SSA name and
label is uniquified by :class:`SSANamer` so the emitted module always
assembles with ``llvm-as``.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass

from scratchv.ir.types import (
    OpCode, DataType, Value, Instruction, BasicBlock, Function, Program,
)


_TYPE_MAP = {
    DataType.FLOAT32: "float",
    DataType.INT32: "i32",
    DataType.FLOAT64: "double",
    DataType.INT64: "i64",
}

_LLVM_FLOAT = "float"
_LLVM_DOUBLE = "double"
_LLVM_I32 = "i32"
_LLVM_I64 = "i64"

_FLOAT_TYPES = ("float", "double")
_INT_TYPES = ("i32", "i64")

_CMP_PRED = {
    "==": ("oeq", "eq"),
    "!=": ("one", "ne"),
    "<": ("olt", "slt"),
    "<=": ("ole", "sle"),
    ">": ("ogt", "sgt"),
    ">=": ("oge", "sge"),
}

_PROLOGUE_MARKER = ";__SCRATCHV_PROLOGUE__"


class LLVMCodegenError(Exception):
    """Raised for unlowerable IR (missing operand, unmatched endfor, ...)."""


class SSANamer:
    """Generates unique SSA register and label names per function."""

    def __init__(self) -> None:
        self._reg_n = 0
        self._label_n = 0
        self._defs: set[str] = set()

    @staticmethod
    def sanitize(name: str) -> str:
        """Map an IR name to a legal LLVM identifier body."""
        s = "".join(
            ch if (ch.isalnum() or ch in "_.") else "_" for ch in str(name)
        )
        if not s or s[0].isdigit():
            s = "v_" + s
        return s

    def fresh(self, hint: str = "r") -> str:
        """Return a fresh register name such as ``%hint_3``."""
        self._reg_n += 1
        return f"%{self.sanitize(hint)}_{self._reg_n}"

    def fresh_label(self, hint: str = "bb") -> str:
        """Return a fresh label name such as ``hint_7`` (no ``%``)."""
        self._label_n += 1
        return f"{self.sanitize(hint)}_{self._label_n}"

    def register_definition(self, reg: str) -> None:
        if reg in self._defs:
            raise LLVMCodegenError(f"duplicate SSA definition: {reg}")
        self._defs.add(reg)

    def registered(self, reg: str) -> bool:
        return reg in self._defs


@dataclass
class LoopContext:
    """State of one structured ``for`` loop (canonical form)."""

    ir_name: str | None
    ptr: str
    value: str
    header: str
    body: str
    exit: str
    limit: int
    step: int = 1


class LLVMCodegen:
    """Translate ScratchV IR Program to LLVM IR text (.ll)."""

    def __init__(self, program: Program, target_triple: str | None = None):
        self.program = program
        self.target_triple = target_triple
        self._lines: list[str] = []
        # IR value name -> current LLVM reference (register or pointer)
        self._named_values: dict[str, str] = {}
        # IR value name -> memory slot (memory-based scalar variables)
        self._slots: dict[str, str] = {}
        # LLVM reference -> LLVM type string
        self._ref_types: dict[str, str] = {}
        # function name -> return type
        self._func_type: dict[str, str] = {}
        # allocas hoisted into the function entry block
        self._prologue: list[str] = []
        self._defined_labels: set[str] = set()
        self._terminated: bool = True
        self._loop_stack: list[LoopContext] = []
        self._current_func: str | None = None
        self._ptr_names: set[str] = set()
        self._namer = SSANamer()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Produce complete LLVM IR module as text."""
        self._lines = []
        self._p("; LLVM IR generated by ScratchV")
        self._p('; ModuleID = "scratchv_module"')
        if self.target_triple is not None:
            self._p(f'target triple = "{self.target_triple}"')
        self._p("")

        self._emit_externals()

        for func in self.program.functions:
            self._emit_function(func)

        return "\n".join(self._lines)

    def save(self, path: str) -> None:
        """Write LLVM IR to a file."""
        with open(path, "w") as f:
            f.write(self.emit())

    # ------------------------------------------------------------------
    # External declarations
    # ------------------------------------------------------------------

    def _emit_externals(self) -> None:
        self._p("declare float @expf(float) nounwind readonly")
        self._p("declare float @tanhf(float) nounwind readonly")
        self._p("declare double @exp(double) nounwind readonly")
        self._p("declare double @tanh(double) nounwind readonly")
        self._p("declare void @print_f32(float) nounwind")
        self._p("")

    def _p(self, line: str = "") -> None:
        self._lines.append(line)

    # ------------------------------------------------------------------
    # Functions
    # ------------------------------------------------------------------

    @staticmethod
    def _infer_function_params(func: Function) -> None:
        """Add undefined external value references as function params."""
        defined: set[str] = {p.name for p in func.params}
        referenced: set[str] = set()

        for block in func.blocks:
            for instr in block.instructions:
                if instr.dest is not None:
                    defined.add(instr.dest.name)
                for op in instr.operands:
                    if not op.is_constant:
                        referenced.add(op.name)

        existing_param_names = {p.name for p in func.params}
        for name in referenced - defined:
            if name not in existing_param_names:
                func.params.append(Value(name=name, dtype=DataType.FLOAT32))

    def _emit_function(self, func: Function) -> None:
        self._current_func = func.name
        self._named_values = {}
        self._slots = {}
        self._ref_types = {}
        self._prologue = []
        self._terminated = False
        self._defined_labels = set()
        self._loop_stack = []
        self._namer = SSANamer()
        self._ptr_names = {
            instr.dest.name
            for block in func.blocks
            for instr in block.instructions
            if instr.opcode is OpCode.ALLOCA and instr.dest is not None
        }

        self._infer_function_params(func)
        self._validate_return_types(func)
        self._check_unbounded_loops(func)

        used_names: set[str] = set()
        params: list[str] = []
        for p in func.params:
            ty = self._value_type(p)
            safe = self._unique_param_name(p.name, used_names)
            params.append(f"{ty} %{safe}")
            self._bind(p.name, f"%{safe}", ty)

        ret_ty = self._function_return_type(func)
        params_str = ", ".join(params)

        self._p(f"define {ret_ty} @{func.name}({params_str}) {{")
        define_idx = len(self._lines) - 1
        marker = len(self._lines)
        self._lines.append(_PROLOGUE_MARKER)

        for block in func.blocks:
            self._emit_block(block)

        if not self._terminated:
            self._p("  unreachable")
            self._terminated = True

        actual_ret = self._first_ret_type(define_idx)
        if actual_ret is not None and actual_ret != ret_ty:
            self._lines[define_idx] = (
                f"define {actual_ret} @{func.name}({params_str}) {{"
            )

        self._lines[marker:marker + 1] = self._prologue
        self._p("}")
        self._p("")

    def _first_ret_type(self, start_idx: int) -> str | None:
        for line in self._lines[start_idx + 1:]:
            stripped = line.strip()
            if stripped.startswith("ret "):
                parts = stripped.split()
                if len(parts) >= 2:
                    return parts[1]
                return "void"
        return None

    @staticmethod
    def _unique_param_name(name: str, used: set[str]) -> str:
        safe = SSANamer.sanitize(name)
        candidate = safe
        n = 1
        while candidate in used:
            n += 1
            candidate = f"{safe}_{n}"
        used.add(candidate)
        return candidate

    def _function_return_type(self, func: Function) -> str:
        if func.returns:
            return self._value_type(func.returns[0])
        for block in func.blocks:
            for instr in block.instructions:
                if instr.opcode is OpCode.RETURN and instr.operands:
                    return self._value_type(instr.operands[0])
        return "void"

    def _validate_return_types(self, func: Function) -> None:
        """Reject mixed ``ret <value>`` / ``ret void`` (illegal LLVM IR).

        ``_first_ret_type`` can only patch the emitted signature to one of
        the two forms, so a function containing both produces a module that
        ``llvm-as`` refuses. Fail loudly instead.
        """
        has_void = False
        value_types: set[str] = set()
        for block in func.blocks:
            for instr in block.instructions:
                if instr.opcode is not OpCode.RETURN:
                    continue
                if instr.operands:
                    value_types.add(self._value_type(instr.operands[0]))
                else:
                    has_void = True
        if has_void and value_types:
            raise LLVMCodegenError(
                f"function {func.name}: void 'ret' mixed with value return "
                f"{sorted(value_types)}; make all returns uniform"
            )
        if len(value_types) > 1:
            raise LLVMCodegenError(
                f"function {func.name}: inconsistent return types "
                f"{sorted(value_types)}"
            )

    def _check_unbounded_loops(self, func: Function) -> None:
        """Reject structured loops whose condition can never change.

        The DSL frontend keeps a fresh ``Value`` per assignment (no phi /
        alloca-based variable identity), so re-assigning a ``while``
        condition variable never updates the slot the header reads. Such a
        loop cannot terminate and would hang ``lli`` or any consumer; fail
        loudly instead of emitting a silently-broken loop.
        """
        blocks = {b.name: b for b in func.blocks}
        for name, block in blocks.items():
            if not block.instructions:
                continue
            br_if = block.instructions[-1]
            if br_if.opcode is not OpCode.BR_IF or not br_if.attrs.get("cmp_op"):
                continue
            targets = [
                t.strip() for t in (br_if.target or "").split(",") if t.strip()
            ]
            if len(targets) < 2:
                continue
            body_name, exit_name = targets[0], targets[1]
            stack = [body_name]
            region: set[str] = set()
            back_edge = False
            while stack:
                current = stack.pop()
                if current == name:
                    back_edge = True
                    continue
                if current in region or current == exit_name:
                    continue
                if current not in blocks:
                    continue
                region.add(current)
                inner = blocks[current]
                if not inner.instructions:
                    continue
                term = inner.instructions[-1]
                if term.opcode is OpCode.BR and term.target:
                    stack.append(term.target.strip())
                elif term.opcode is OpCode.BR_IF:
                    stack.extend(
                        t.strip() for t in (term.target or "").split(",")
                        if t.strip()
                    )
            if not back_edge:
                continue
            has_return = any(
                instr.opcode is OpCode.RETURN
                for block_name in region
                for instr in blocks[block_name].instructions
            )
            if has_return:
                continue
            cond_names = [
                v.name for v in br_if.operands
                if not v.is_constant and v.const_value is None
            ]
            defined = {
                instr.dest.name
                for block_name in region
                for instr in blocks[block_name].instructions
                if instr.dest is not None
            }
            if not any(n in defined for n in cond_names):
                reason = (
                    "its condition operands are constant"
                    if not cond_names
                    else f"condition operands {cond_names} are not modified "
                         f"in the loop body"
                )
                raise LLVMCodegenError(
                    f"function {func.name}: loop at '{name}' can never exit "
                    f"({reason}); DSL variables have static SSA semantics, "
                    f"so reassigning a loop condition variable is unsupported"
                )

    # ------------------------------------------------------------------
    # Basic blocks and control-flow state machine
    # ------------------------------------------------------------------

    def _emit_block(self, block: BasicBlock) -> None:
        self._start_block(block.name)
        self._p(f"; --- {block.name} ---")
        for instr in block.instructions:
            self._emit_instruction(instr)

    def _start_block(self, label: str) -> None:
        """Close the current block (fallthrough) and open ``label``."""
        if not label:
            label = self._namer.fresh_label("bb")
        if label in self._defined_labels:
            label = self._namer.fresh_label(label)
            while label in self._defined_labels:
                label = self._namer.fresh_label(label)
        if not self._terminated:
            self._p(f"  br label %{label}")
        self._p(f"{label}:")
        self._defined_labels.add(label)
        self._terminated = False

    def _terminate(self, line: str) -> None:
        if self._terminated:
            raise LLVMCodegenError("terminator emitted twice in one block")
        self._p(f"  {line}")
        self._terminated = True

    # ------------------------------------------------------------------
    # Instructions
    # ------------------------------------------------------------------

    def _emit_instruction(self, instr: Instruction) -> None:
        if self._terminated:
            self._start_block(self._namer.fresh_label("dead"))
        handler = getattr(self, f"_emit_{instr.opcode.value}", None)
        if handler is None:
            handler = self._emit_unsupported
        handler(instr)
        self._flush_dest(instr)

    def _flush_dest(self, instr: Instruction) -> None:
        """Store a just-defined scalar value into its memory slot."""
        if instr.dest is None:
            return
        name = instr.dest.name
        reg = self._named_values.get(name)
        slot = self._slots.get(name)
        if reg is None or slot is None or self._terminated:
            return
        ty = self._ref_types.get(reg)
        if ty is None or ty.endswith("*"):
            return
        self._p(f"  store {ty} {reg}, {ty}* {slot}")

    def _emit_unsupported(self, instr: Instruction) -> None:
        """Fail loudly: silently approximating an op would corrupt results."""
        raise LLVMCodegenError(
            f"opcode not lowered by the LLVM backend: "
            f"{instr.opcode.value} (destination "
            f"{instr.dest.name if instr.dest else '<none>'})"
        )

    # ------------------------------------------------------------------
    # Naming / value binding helpers
    # ------------------------------------------------------------------

    def _fresh(self, hint: str = "r") -> str:
        return self._namer.fresh(hint)

    def _fresh_label(self, hint: str = "bb") -> str:
        return self._namer.fresh_label(hint)

    def _bind(self, name: str, ref: str, llvm_ty: str) -> None:
        self._named_values[name] = ref
        self._ref_types[ref] = llvm_ty

    def _dest(self, instr: Instruction) -> str:
        """Get or create an LLVM register for a scalar destination.

        Tensor destinations must be lowered through :meth:`_dest_buffer` (or
        :meth:`_emit_map` for elementwise ops); requesting a scalar register
        for a shaped value would emit illegal IR, so it fails loudly.
        """
        if instr.dest is None:
            return ""
        if (self._is_pointer_value(instr.dest)
                and instr.opcode is not OpCode.ALLOCA):
            raise LLVMCodegenError(
                f"{instr.opcode.value}: tensor destination "
                f"'{instr.dest.name}' requires buffer lowering"
            )
        name = instr.dest.name
        if name in self._named_values:
            return self._named_values[name]
        reg = self._fresh(name)
        ty = self._value_type(instr.dest)
        self._bind(name, reg, ty)
        self._ensure_slot(name, ty)
        return reg

    def _ensure_slot(self, name: str, ty: str) -> str | None:
        """Allocate (once) a memory slot for a scalar IR variable."""
        if ty.endswith("*"):
            return None
        slot = self._slots.get(name)
        if slot is None:
            slot = self._alloc_slot(ty, 1, f"{name}_mem")
            self._slots[name] = slot
        return slot

    def _bind_dest(self, instr: Instruction, ref: str, ty: str) -> None:
        """Bind an instruction destination and give it a scalar slot."""
        if instr.dest is None:
            return
        self._bind(instr.dest.name, ref, ty)
        self._ensure_slot(instr.dest.name, ty)

    def _op(self, instr: Instruction, idx: int) -> str:
        """Resolve operand idx to an LLVM value reference."""
        if idx >= len(instr.operands):
            raise LLVMCodegenError(
                f"missing operand {idx} for {instr.opcode.value}"
            )
        return self._value_ref(instr.operands[idx])

    def _value_ref(self, val: Value) -> str:
        """Get LLVM reference for a Value, materializing if necessary."""
        if val.name in self._named_values:
            slot = self._slots.get(val.name)
            if slot is not None:
                ty = self._ref_types.get(self._named_values[val.name])
                if ty is None or not ty.endswith("*"):
                    return self._load(ty or _llvm_type(val.dtype),
                                      slot, f"{val.name}_ld")
            return self._named_values[val.name]
        if val.is_constant and val.const_value is not None:
            return _llvm_const(val)
        base = _llvm_type(val.dtype)
        if self._is_pointer_value(val):
            count = self._shape_count(val)
            ptr = self._alloc_slot(base, count, "tbuf")
            self._bind(val.name, ptr, base + "*")
            return ptr
        reg = self._materialize_const(0, base, "undef")
        self._bind(val.name, reg, base)
        return reg

    def _value_type(self, val: Value) -> str:
        base = _llvm_type(val.dtype)
        if self._is_pointer_value(val):
            return base + "*"
        ref = self._named_values.get(val.name)
        if ref is not None and self._ref_types.get(ref, "").endswith("*"):
            return self._ref_types[ref]
        return base

    def _is_pointer_value(self, val: Value) -> bool:
        return bool(val.shape) or val.name in self._ptr_names

    @staticmethod
    def _shape_count(val: Value) -> int:
        """Element count denoted by a value's shape (at least 1)."""
        count = 1
        for dim in val.shape:
            count *= max(1, int(dim))
        return count

    def _is_tensor_operand(self, val: Value) -> bool:
        """Whether ``val`` is backed by a buffer (constants are scalars)."""
        if val.is_constant and val.const_value is not None:
            return False
        return self._is_pointer_value(val)

    def _require_elements(self, instr: Instruction, idx: int,
                          needed: int, what: str) -> None:
        """Fail loudly when an operand cannot supply ``needed`` elements.

        Scalar operands are spilled to a single-element buffer by
        :meth:`_ptr_of`; letting a tensor loop run past that buffer would be
        an out-of-bounds read, so multi-element requests on scalars (and
        under-sized shaped operands) are rejected.
        """
        if idx >= len(instr.operands):
            raise LLVMCodegenError(
                f"missing operand {idx} for {instr.opcode.value}"
            )
        val = instr.operands[idx]
        if not self._is_tensor_operand(val):
            if needed > 1:
                raise LLVMCodegenError(
                    f"{instr.opcode.value}: scalar operand '{val.name}' "
                    f"cannot supply {needed} elements for {what}; pass a "
                    f"value with a shape"
                )
            return
        available = self._shape_count(val)
        if available < needed:
            raise LLVMCodegenError(
                f"{instr.opcode.value}: operand '{val.name}' has "
                f"{available} element(s) but {what} needs {needed}"
            )

    def _type_of_operand(self, instr: Instruction, idx: int) -> str:
        if idx >= len(instr.operands):
            return "float"
        val = instr.operands[idx]
        if (val.is_constant and val.const_value is not None
                and val.name not in self._named_values):
            return _llvm_type(val.dtype)
        ref = self._op(instr, idx)
        return self._ref_types.get(ref, _llvm_type(val.dtype))

    def _infer_type(self, instr: Instruction) -> str:
        if instr.dest is not None:
            return _llvm_type(instr.dest.dtype)
        for op in instr.operands:
            return _llvm_type(op.dtype)
        return "float"

    # ------------------------------------------------------------------
    # Memory helpers
    # ------------------------------------------------------------------

    def _alloc_slot(self, elem_ty: str, count: int = 1,
                    hint: str = "slot") -> str:
        """Allocate stack storage in the entry prologue; return pointer ref."""
        reg = self._fresh(hint)
        self._prologue.append(
            f"  {reg} = alloca {elem_ty}, i32 {max(1, int(count))}"
        )
        self._ref_types[reg] = elem_ty + "*"
        return reg

    def _dest_buffer(self, instr: Instruction, count: int,
                     elem_ty: str) -> str:
        """Return a destination buffer pointer, binding ``instr.dest``."""
        count = max(1, int(count))
        if instr.dest is None:
            return self._alloc_slot(elem_ty, count, "tmp")
        name = instr.dest.name
        ref = self._named_values.get(name)
        if ref is not None and self._ref_types.get(ref, "").endswith("*"):
            return ref
        ptr = self._alloc_slot(elem_ty, count, "buf")
        self._bind(name, ptr, elem_ty + "*")
        return ptr

    def _ptr_of(self, instr: Instruction, idx: int, ty: str = "float") -> str:
        """Use operand idx as a pointer; scalar operands are spilled."""
        if idx >= len(instr.operands):
            raise LLVMCodegenError(
                f"missing pointer operand {idx} for {instr.opcode.value}"
            )
        val = instr.operands[idx]
        ref = self._value_ref(val)
        rty = self._ref_types.get(ref, "")
        if rty.endswith("*"):
            return ref
        ptr = self._alloc_slot(ty, 1, "spin")
        if not ref.startswith("%") and val.is_constant:
            ref = _llvm_const_val(val.const_value, ty)
        self._p(f"  store {ty} {ref}, {ty}* {ptr}")
        return ptr

    def _ptr_elem_ty(self, ptr: str, fallback: str) -> str:
        """Element type of a known pointer operand, else ``fallback``."""
        pty = self._ref_types.get(ptr, "")
        if pty.endswith("*") and pty[:-1] in _FLOAT_TYPES:
            return pty[:-1]
        return fallback

    def _emit_map(self, instr: Instruction, apply) -> None:
        """Lower an elementwise op whose destination carries a shape.

        Each element of the destination is computed by calling ``apply`` with
        the per-element operand refs; shaped operands are indexed element by
        element, scalar operands are broadcast.
        """
        assert instr.dest is not None
        count = self._shape_count(instr.dest)
        ty = _llvm_type(instr.dest.dtype)
        broadcast: set[int] = set()
        for idx, val in enumerate(instr.operands):
            if not self._is_tensor_operand(val):
                continue
            available = self._shape_count(val)
            if available not in (1, count):
                raise LLVMCodegenError(
                    f"{instr.opcode.value}: operand '{val.name}' has "
                    f"{available} element(s), destination needs {count}"
                )
            if available == 1 and count > 1:
                broadcast.add(idx)
        if ty not in _FLOAT_TYPES and instr.opcode in (
                OpCode.EXP, OpCode.GELU, OpCode.SIGMOID):
            raise LLVMCodegenError(
                f"{instr.opcode.value}: integer tensor destinations are not "
                f"supported"
            )
        out = self._dest_buffer(instr, count, ty)
        ctx = self._loop_open(count, None, "ew_i")
        args: list[str] = []
        for idx, val in enumerate(instr.operands):
            if not self._is_tensor_operand(val):
                args.append(self._operand_for(instr, idx, ty, "ew_s"))
                continue
            ptr = self._ptr_of(instr, idx, ty)
            if idx in broadcast:
                args.append(self._load(ty, ptr, "ew_v"))
            else:
                elem = self._gep(ty, ptr, ctx.value, "ew_p")
                args.append(self._load(ty, elem, "ew_v"))
        result = apply(args)
        out_ptr = self._gep(ty, out, ctx.value, "ew_o")
        self._p(f"  store {ty} {result}, {ty}* {out_ptr}")
        self._loop_close(ctx)
        self._finalize_from_buffer(instr, out, ty)

    def _materialize_const(self, value: float | int, ty: str,
                           hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        if ty in _FLOAT_TYPES:
            self._p(f"  {reg} = fadd {ty} {_float_literal(float(value))}, 0.0")
        else:
            self._p(f"  {reg} = add {ty} 0, {int(value)}")
        self._ref_types[reg] = ty
        return reg

    def _coerce_operand(self, ref: str, from_ty: str,
                        to_ty: str, hint: str) -> str:
        if from_ty == to_ty:
            return ref
        if from_ty.endswith("*") or to_ty.endswith("*"):
            raise LLVMCodegenError(f"no coercion {from_ty} -> {to_ty}")
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        if from_ty in _INT_TYPES and to_ty in _FLOAT_TYPES:
            self._p(f"  {reg} = sitofp {from_ty} {ref} to {to_ty}")
        elif from_ty in _FLOAT_TYPES and to_ty in _INT_TYPES:
            self._p(f"  {reg} = fptosi {from_ty} {ref} to {to_ty}")
        elif from_ty in _FLOAT_TYPES and to_ty in _FLOAT_TYPES:
            op = "fpext" if to_ty == "double" else "fptrunc"
            self._p(f"  {reg} = {op} {from_ty} {ref} to {to_ty}")
        elif from_ty in _INT_TYPES and to_ty in _INT_TYPES:
            op = "sext" if to_ty == "i64" else "trunc"
            self._p(f"  {reg} = {op} {from_ty} {ref} to {to_ty}")
        else:
            raise LLVMCodegenError(f"no coercion {from_ty} -> {to_ty}")
        self._ref_types[reg] = to_ty
        return reg

    def _operand_for(self, instr: Instruction, idx: int,
                     target_ty: str, hint: str) -> str:
        val = instr.operands[idx]
        if (val.is_constant and val.const_value is not None
                and val.name not in self._named_values):
            return _llvm_const_val(val.const_value, target_ty)
        ref = self._op(instr, idx)
        from_ty = self._ref_types.get(ref, _llvm_type(val.dtype))
        if from_ty.endswith("*") and not target_ty.endswith("*"):
            elem_ty = from_ty[:-1]
            ref = self._load(elem_ty, ref, f"{hint}_ld")
            from_ty = elem_ty
        return self._coerce_operand(ref, from_ty, target_ty, hint)

    def _gep(self, ty: str, base: str, idx, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = getelementptr {ty}, {ty}* {base}, i32 {idx}")
        self._ref_types[reg] = ty + "*"
        return reg

    def _load(self, ty: str, ptr: str, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = load {ty}, {ty}* {ptr}")
        self._ref_types[reg] = ty
        return reg

    def _bin(self, op: str, ty: str, lhs, rhs, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = {op} {ty} {lhs}, {rhs}")
        self._ref_types[reg] = ty
        return reg

    def _un(self, op: str, ty: str, src, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = {op} {ty} {src}")
        self._ref_types[reg] = ty
        return reg

    def _call_math(self, name: str, ty: str, arg: str, hint: str) -> str:
        fn = name + ("f" if ty == "float" else "")
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = call {ty} @{fn}({ty} {arg})")
        self._ref_types[reg] = ty
        return reg

    def _iadd(self, lhs, rhs, hint: str):
        if isinstance(lhs, int) and isinstance(rhs, int):
            return lhs + rhs
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = add i32 {lhs}, {rhs}")
        self._ref_types[reg] = "i32"
        return reg

    def _isub(self, lhs, rhs, hint: str):
        if isinstance(lhs, int) and isinstance(rhs, int):
            return lhs - rhs
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = sub i32 {lhs}, {rhs}")
        self._ref_types[reg] = "i32"
        return reg

    def _imul(self, lhs, rhs, hint: str):
        if isinstance(lhs, int) and isinstance(rhs, int):
            return lhs * rhs
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = mul i32 {lhs}, {rhs}")
        self._ref_types[reg] = "i32"
        return reg

    def _icmp(self, pred: str, lhs, rhs, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = icmp {pred} i32 {lhs}, {rhs}")
        self._ref_types[reg] = "i1"
        return reg

    def _bin_i1(self, op: str, lhs: str, rhs: str, hint: str) -> str:
        reg = self._fresh(hint)
        self._namer.register_definition(reg)
        self._p(f"  {reg} = {op} i1 {lhs}, {rhs}")
        self._ref_types[reg] = "i1"
        return reg

    # ------------------------------------------------------------------
    # Arithmetic
    # ------------------------------------------------------------------

    def _emit_binary(self, instr: Instruction, fop: str, iop: str) -> None:
        ty = self._infer_type(instr)
        op = fop if ty in _FLOAT_TYPES else iop
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr,
                lambda args: self._bin(op, ty, args[0], args[1], "ew_b"),
            )
            return
        lhs = self._operand_for(instr, 0, ty, "cvt_l")
        rhs = self._operand_for(instr, 1, ty, "cvt_r")
        dst = self._dest(instr)
        self._p(f"  {dst} = {op} {ty} {lhs}, {rhs}")

    def _emit_add(self, instr: Instruction) -> None:
        self._emit_binary(instr, "fadd", "add")

    def _emit_sub(self, instr: Instruction) -> None:
        self._emit_binary(instr, "fsub", "sub")

    def _emit_mul(self, instr: Instruction) -> None:
        self._emit_binary(instr, "fmul", "mul")

    def _emit_div(self, instr: Instruction) -> None:
        self._emit_binary(instr, "fdiv", "sdiv")

    def _emit_neg(self, instr: Instruction) -> None:
        ty = self._infer_type(instr)
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr,
                lambda args: self._un("fneg", ty, args[0], "ew_n")
                if ty in _FLOAT_TYPES
                else self._bin("sub", ty, 0, args[0], "ew_n"),
            )
            return
        src = self._operand_for(instr, 0, ty, "cvt")
        dst = self._dest(instr)
        if ty in _FLOAT_TYPES:
            self._p(f"  {dst} = fneg {ty} {src}")
        else:
            self._p(f"  {dst} = sub {ty} 0, {src}")

    def _emit_exp(self, instr: Instruction) -> None:
        ty = self._infer_type(instr)
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr,
                lambda args: self._call_math("exp", ty, args[0], "ew_e"),
            )
            return
        if ty in _FLOAT_TYPES:
            src = self._operand_for(instr, 0, ty, "cvt")
            dst = self._dest(instr)
            fn = "exp" if ty == "double" else "expf"
            self._p(f"  {dst} = call {ty} @{fn}({ty} {src})")
            return
        src = self._operand_for(instr, 0, "float", "cvt")
        exp_reg = self._call_math("exp", "float", src, "expf")
        dst = self._dest(instr)
        self._p(f"  {dst} = fptosi float {exp_reg} to {ty}")
        self._ref_types[dst] = ty

    # ------------------------------------------------------------------
    # Constants & memory
    # ------------------------------------------------------------------

    def _emit_load_const(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        raw_val = instr.attrs.get("value", 0)
        ty = _llvm_type(instr.dest.dtype) if instr.dest else "float"
        if ty in _FLOAT_TYPES:
            lit = _float_literal(float(raw_val))
            self._p(f"  {dst} = fadd {ty} 0.0, {lit}")
        else:
            self._p(f"  {dst} = add {ty} 0, {int(raw_val)}")

    def _emit_load(self, instr: Instruction) -> None:
        ty = _llvm_type(instr.dest.dtype) if instr.dest else "float"
        ptr = self._op(instr, 0)
        pty = self._ref_types.get(ptr, "")
        if pty.endswith("*"):
            ty = pty[:-1]
        else:
            ptr = self._ptr_of(instr, 0, ty)
        dst = self._dest(instr)
        self._p(f"  {dst} = load {ty}, {ty}* {ptr}")
        self._ref_types[dst] = ty

    def _emit_store(self, instr: Instruction) -> None:
        ptr = self._op(instr, 0)
        pty = self._ref_types.get(ptr, "")
        if not pty.endswith("*"):
            raise LLVMCodegenError("store target is not a pointer")
        elem_ty = pty[:-1]
        val = self._operand_for(instr, 1, elem_ty, "stv")
        self._p(f"  store {elem_ty} {val}, {elem_ty}* {ptr}")

    def _emit_alloca(self, instr: Instruction) -> None:
        dst = self._dest(instr)
        size = instr.attrs.get("size", 4)
        try:
            size = int(size)
        except (TypeError, ValueError):
            size = 1
        ty = _llvm_type(instr.dest.dtype) if instr.dest else "float"
        self._p(f"  {dst} = alloca {ty}, i32 {max(1, size)}")
        self._ref_types[dst] = ty + "*"

    # ------------------------------------------------------------------
    # Control flow
    # ------------------------------------------------------------------

    def _emit_for(self, instr: Instruction) -> None:
        limit = max(0, self._as_int(instr.attrs.get("end", 0), 0))
        start = self._as_int(instr.attrs.get("start", 0), 0)
        step = self._as_int(instr.attrs.get("step", 1), 1) or 1
        ir_name = instr.dest.name if instr.dest is not None else None
        self._loop_open(limit, ir_name, "loop_i", start, step)

    def _emit_endfor(self, instr: Instruction) -> None:
        if not self._loop_stack:
            raise LLVMCodegenError("endfor without matching for")
        self._loop_close(self._loop_stack[-1])

    def _loop_open(self, limit: int, ir_name: str | None, hint: str,
                   start: int = 0, step: int = 1) -> LoopContext:
        limit = max(0, int(limit))
        start = int(start)
        step = int(step) or 1

        ptr = self._alloc_slot("i32", 1, f"{hint}_ptr")
        self._p(f"  store i32 {start}, i32* {ptr}")
        header = self._fresh_label(f"{hint}_hdr")
        body = self._fresh_label(f"{hint}_bdy")
        exit_ = self._fresh_label(f"{hint}_ext")

        self._start_block(header)
        iv = self._fresh(f"{hint}_ld")
        self._namer.register_definition(iv)
        self._p(f"  {iv} = load i32, i32* {ptr}")
        cond = self._fresh(f"{hint}_cond")
        self._namer.register_definition(cond)
        self._p(f"  {cond} = icmp slt i32 {iv}, {limit}")
        self._terminate(f"br i1 {cond}, label %{body}, label %{exit_}")
        self._start_block(body)

        ctx = LoopContext(ir_name, ptr, iv, header, body, exit_, limit, step)
        self._loop_stack.append(ctx)
        if ir_name is not None:
            self._bind(ir_name, iv, "i32")
        return ctx

    def _loop_close(self, ctx: LoopContext) -> None:
        if not self._loop_stack or self._loop_stack[-1] is not ctx:
            raise LLVMCodegenError("endfor without matching for")
        self._loop_stack.pop()
        if not self._terminated:
            cur = self._fresh("iv_cur")
            self._namer.register_definition(cur)
            self._p(f"  {cur} = load i32, i32* {ctx.ptr}")
            nxt = self._fresh("iv_nxt")
            self._namer.register_definition(nxt)
            self._p(f"  {nxt} = add i32 {cur}, {ctx.step}")
            self._p(f"  store i32 {nxt}, i32* {ctx.ptr}")
            self._terminate(f"br label %{ctx.header}")
        self._start_block(ctx.exit)

    def _emit_br(self, instr: Instruction) -> None:
        target = (instr.target or "").strip()
        if not target:
            self._terminate("unreachable")
        else:
            self._terminate(f"br label %{target}")

    def _emit_br_if(self, instr: Instruction) -> None:
        targets = (instr.target or "").split(",")
        true_t = targets[0].strip() if targets else ""
        false_t = targets[1].strip() if len(targets) > 1 else true_t
        if not false_t:
            false_t = true_t
        if not true_t:
            self._terminate("unreachable")
            return

        cmp_op = instr.attrs.get("cmp_op")
        if cmp_op and len(instr.operands) >= 2:
            key = str(cmp_op)
            if key not in _CMP_PRED:
                raise LLVMCodegenError(f"unknown comparison operator: {key}")
            ty = self._infer_type(instr)
            lhs = self._operand_for(instr, 0, ty, "cmpl")
            rhs = self._operand_for(instr, 1, ty, "cmpr")
            fpred, ipred = _CMP_PRED[key]
            is_float = ty in _FLOAT_TYPES
            kind = "fcmp" if is_float else "icmp"
            pred = fpred if is_float else ipred
            cond = self._fresh(f"brc_{kind}")
            self._namer.register_definition(cond)
            self._p(f"  {cond} = {kind} {pred} {ty} {lhs}, {rhs}")
            self._ref_types[cond] = "i1"
        elif instr.operands:
            cond = self._op(instr, 0)
            cty = self._ref_types.get(cond) or self._type_of_operand(instr, 0)
            if cty.endswith("*"):
                elem_ty = cty[:-1]
                cond = self._load(elem_ty, cond, "brc_ld")
                cty = elem_ty
            if cty == "i32":
                cond = self._icmp("ne", cond, 0, "brc")
            elif cty in _FLOAT_TYPES:
                cmp_reg = self._fresh("brc")
                self._namer.register_definition(cmp_reg)
                self._p(f"  {cmp_reg} = fcmp one {cty} {cond}, 0.0")
                self._ref_types[cmp_reg] = "i1"
                cond = cmp_reg
            elif cty == "i64":
                cmp_reg = self._fresh("brc")
                self._namer.register_definition(cmp_reg)
                self._p(f"  {cmp_reg} = icmp ne i64 {cond}, 0")
                self._ref_types[cmp_reg] = "i1"
                cond = cmp_reg
        else:
            self._terminate("unreachable")
            return

        self._terminate(f"br i1 {cond}, label %{true_t}, label %{false_t}")

    def _emit_return(self, instr: Instruction) -> None:
        if instr.operands:
            val = instr.operands[0]
            ref = self._value_ref(val)
            ty = self._ref_types.get(ref)
            if ty is None:
                ty = self._value_type(val)
            self._terminate(f"ret {ty} {ref}")
        else:
            self._terminate("ret void")

    def _emit_label(self, instr: Instruction) -> None:
        """IR labels become LLVM block labels."""
        if instr.target:
            self._start_block(instr.target)

    # ------------------------------------------------------------------
    # Neural-network ops
    # ------------------------------------------------------------------

    def _finalize_from_acc(self, instr: Instruction,
                           acc: str, ty: str) -> None:
        """Result scalar lives in ``acc``; publish it to ``instr.dest``."""
        if instr.dest is None:
            return
        value = self._load(ty, acc, "res")
        if self._is_pointer_value(instr.dest):
            count = self._shape_count(instr.dest)
            buf = self._dest_buffer(instr, count, ty)
            self._p(f"  store {ty} {value}, {ty}* {buf}")
        else:
            self._bind_dest(instr, value, ty)

    def _finalize_from_buffer(self, instr: Instruction,
                              buf: str, ty: str) -> None:
        """Result tensor lives in ``buf``; load scalar if dest is scalar."""
        if instr.dest is None:
            return
        if not self._is_pointer_value(instr.dest):
            value = self._load(ty, buf, "res")
            self._bind_dest(instr, value, ty)

    def _dim_of(self, instr: Instruction, keys: tuple[str, ...],
                default: int = 1, operand: int | None = None,
                axis: int | None = None) -> int:
        for key in keys:
            value = instr.attrs.get(key)
            if isinstance(value, (int, float)) and int(value) > 0:
                return int(value)
        if operand is not None and operand < len(instr.operands):
            shape = instr.operands[operand].shape
            if shape:
                idx = axis if axis is not None else 0
                if -len(shape) <= idx < len(shape):
                    dim = int(shape[idx])
                    if dim > 0:
                        return dim
        return default

    @staticmethod
    def _as_int(value, default: int = 0) -> int:
        if isinstance(value, Value):
            if value.const_value is not None:
                return int(value.const_value)
            return default
        try:
            return int(value)
        except (TypeError, ValueError):
            return default

    def _relu_scalar(self, ty: str, src: str) -> str:
        reg = self._fresh("relu_r")
        self._namer.register_definition(reg)
        cmp_reg = self._fresh("cmp")
        self._namer.register_definition(cmp_reg)
        if ty in _FLOAT_TYPES:
            self._p(f"  {cmp_reg} = fcmp ogt {ty} {src}, 0.0")
            self._p(f"  {reg} = select i1 {cmp_reg}, {ty} {src}, {ty} 0.0")
        else:
            self._p(f"  {cmp_reg} = icmp sgt {ty} {src}, 0")
            self._p(f"  {reg} = select i1 {cmp_reg}, {ty} {src}, {ty} 0")
        self._ref_types[reg] = ty
        return reg

    def _emit_relu(self, instr: Instruction) -> None:
        ty = self._infer_type(instr)
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr, lambda args: self._relu_scalar(ty, args[0])
            )
            return
        src = self._operand_for(instr, 0, ty, "cvt")
        dst = self._dest(instr)
        cmp_reg = self._fresh("cmp")
        self._namer.register_definition(cmp_reg)
        if ty in _FLOAT_TYPES:
            self._p(f"  {cmp_reg} = fcmp ogt {ty} {src}, 0.0")
            self._p(f"  {dst} = select i1 {cmp_reg}, {ty} {src}, {ty} 0.0")
        else:
            self._p(f"  {cmp_reg} = icmp sgt {ty} {src}, 0")
            self._p(f"  {dst} = select i1 {cmp_reg}, {ty} {src}, {ty} 0")

    def _gelu_scalar(self, ty: str, x: str) -> str:
        """GELU(x) = 0.5*x*(1 + tanh(sqrt(2/pi)*(x + 0.044715*x^3)))."""
        t1 = self._bin("fmul", ty, x, x, "gelu_t1")
        x3 = self._bin("fmul", ty, t1, x, "gelu_x3")
        in1 = self._bin("fmul", ty, _float_literal(0.044715), x3, "gelu_in1")
        in2 = self._bin("fadd", ty, in1, x, "gelu_in2")
        inner = self._bin(
            "fmul", ty, in2, _float_literal(0.7978845608028654), "gelu_inner"
        )
        tanh_reg = self._call_math("tanh", ty, inner, "gelu_tanh")
        p1 = self._bin("fadd", ty, "1.0", tanh_reg, "gelu_p1")
        hx = self._bin("fmul", ty, x, "0.5", "gelu_hx")
        return self._bin("fmul", ty, hx, p1, "gelu_out")

    def _sigmoid_scalar(self, ty: str, x: str) -> str:
        """Sigmoid(x) = 1 / (1 + exp(-x))."""
        neg = self._fresh("sig_neg")
        self._namer.register_definition(neg)
        self._p(f"  {neg} = fneg {ty} {x}")
        self._ref_types[neg] = ty
        exp_reg = self._call_math("exp", ty, neg, "sig_exp")
        den = self._bin("fadd", ty, "1.0", exp_reg, "sig_den")
        return self._bin("fdiv", ty, "1.0", den, "sig_out")

    def _emit_gelu(self, instr: Instruction) -> None:
        """GELU(x) = 0.5*x*(1 + tanh(sqrt(2/pi)*(x + 0.044715*x^3)))."""
        ty = self._infer_type(instr)
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr, lambda args: self._gelu_scalar(ty, args[0])
            )
            return
        x = self._operand_for(instr, 0, ty, "cvt")
        if instr.dest is None:
            return
        out = self._gelu_scalar(ty, x)
        self._bind_dest(instr, out, ty)

    def _emit_sigmoid(self, instr: Instruction) -> None:
        """Sigmoid(x) = 1 / (1 + exp(-x))."""
        ty = self._infer_type(instr)
        if instr.dest is not None and self._is_pointer_value(instr.dest):
            self._emit_map(
                instr, lambda args: self._sigmoid_scalar(ty, args[0])
            )
            return
        x = self._operand_for(instr, 0, ty, "cvt")
        if instr.dest is None:
            return
        out = self._sigmoid_scalar(ty, x)
        self._bind_dest(instr, out, ty)

    def _emit_softmax(self, instr: Instruction) -> None:
        """Numerically stable softmax over the last axis (three passes)."""
        ty = self._infer_type(instr)
        axis = instr.attrs.get("axis", -1)
        if axis != -1:
            raise LLVMCodegenError(
                f"softmax: only axis=-1 is supported, got axis={axis}"
            )
        x = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(x, ty)
        shape = tuple(instr.operands[0].shape)
        if shape:
            n = max(1, int(shape[-1]))
            rows = 1
            for dim in shape[:-1]:
                rows *= max(1, int(dim))
        else:
            n = max(1, self._dim_of(
                instr, ("length", "len", "n"), 1, operand=0, axis=-1
            ))
            rows = 1
        total = rows * n
        if instr.dest is not None and instr.dest.shape:
            dest_count = self._shape_count(instr.dest)
            if dest_count != total:
                raise LLVMCodegenError(
                    f"softmax: destination shape needs {dest_count} "
                    f"element(s) but input provides {total}"
                )
            total = dest_count
        self._require_elements(instr, 0, total, "softmax")
        out = self._dest_buffer(instr, total, ty)
        row_ctx = self._loop_open(rows, None, "sm_row") if rows > 1 else None
        row_off = row_ctx.value if row_ctx is not None else None

        def flat(idx: str, hint: str) -> str:
            if row_off is None:
                return idx
            return self._iadd(
                self._imul(row_off, n, f"{hint}_r"), idx, hint
            )

        max_ptr = self._alloc_slot(ty, 1, "sm_m")
        self._p(f"  store {ty} {_float_literal(-3.4e38)}, {ty}* {max_ptr}")
        ctx = self._loop_open(n, None, "sm_max_i")
        xv = self._load(
            ty, self._gep(ty, x, flat(ctx.value, "sm_xp1"), "sm_xp1"), "sm_xv1"
        )
        mv = self._load(ty, max_ptr, "sm_mv1")
        cmp_reg = self._fresh("sm_cmp1")
        self._namer.register_definition(cmp_reg)
        self._p(f"  {cmp_reg} = fcmp ogt {ty} {xv}, {mv}")
        new_max = self._fresh("sm_new1")
        self._namer.register_definition(new_max)
        self._p(f"  {new_max} = select i1 {cmp_reg}, {ty} {xv}, {ty} {mv}")
        self._p(f"  store {ty} {new_max}, {ty}* {max_ptr}")
        self._loop_close(ctx)

        sum_ptr = self._alloc_slot(ty, 1, "sm_s")
        self._p(f"  store {ty} 0.0, {ty}* {sum_ptr}")
        ctx = self._loop_open(n, None, "sm_sum_i")
        xv = self._load(
            ty, self._gep(ty, x, flat(ctx.value, "sm_xp2"), "sm_xp2"), "sm_xv2"
        )
        mv = self._load(ty, max_ptr, "sm_mv2")
        diff = self._bin("fsub", ty, xv, mv, "sm_diff2")
        exp_reg = self._call_math("exp", ty, diff, "sm_exp2")
        sv = self._load(ty, sum_ptr, "sm_sv2")
        new_sum = self._bin("fadd", ty, sv, exp_reg, "sm_new2")
        self._p(f"  store {ty} {new_sum}, {ty}* {sum_ptr}")
        self._loop_close(ctx)

        ctx = self._loop_open(n, None, "sm_div_i")
        xv = self._load(
            ty, self._gep(ty, x, flat(ctx.value, "sm_xp3"), "sm_xp3"), "sm_xv3"
        )
        mv = self._load(ty, max_ptr, "sm_mv3")
        diff = self._bin("fsub", ty, xv, mv, "sm_diff3")
        exp_reg = self._call_math("exp", ty, diff, "sm_exp3")
        sv = self._load(ty, sum_ptr, "sm_sv3")
        quotient = self._bin("fdiv", ty, exp_reg, sv, "sm_q3")
        op = self._gep(ty, out, flat(ctx.value, "sm_op3"), "sm_op3")
        self._p(f"  store {ty} {quotient}, {ty}* {op}")
        self._loop_close(ctx)

        if row_ctx is not None:
            self._loop_close(row_ctx)
        self._finalize_from_buffer(instr, out, ty)

    def _emit_maxpool(self, instr: Instruction) -> None:
        """2D max pooling (NCHW layout, no padding)."""
        ty = self._infer_type(instr)
        x = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(x, ty)
        shape = tuple(instr.operands[0].shape)
        if len(shape) >= 3:
            channels, height, width = shape[-3], shape[-2], shape[-1]
        else:
            channels = height = width = 1
        channels = max(1, int(channels))
        height = max(1, int(height))
        width = max(1, int(width))
        self._require_elements(
            instr, 0, channels * height * width, "maxpool input"
        )
        kernel = max(1, self._dim_of(instr, ("kernel", "kernel_shape"), 2))
        stride = max(1, self._dim_of(instr, ("stride", "strides"), 2))
        out_h = max(0, (height - kernel) // stride + 1)
        out_w = max(0, (width - kernel) // stride + 1)
        out = self._dest_buffer(instr, channels * out_h * out_w, ty)

        c_ctx = self._loop_open(channels, None, "mp_c")
        h_ctx = self._loop_open(out_h, None, "mp_oh")
        w_ctx = self._loop_open(out_w, None, "mp_ow")
        max_ptr = self._alloc_slot(ty, 1, "mp_max")
        self._p(f"  store {ty} {_float_literal(-3.4e38)}, {ty}* {max_ptr}")

        kh_ctx = self._loop_open(kernel, None, "mp_kh")
        ih = self._iadd(
            self._imul(h_ctx.value, stride, "mp_ih0"),
            kh_ctx.value, "mp_ih",
        )
        in_h = self._imul(ih, width, "mp_in_h")
        kw_ctx = self._loop_open(kernel, None, "mp_kw")
        iw = self._iadd(
            self._imul(w_ctx.value, stride, "mp_iw0"),
            kw_ctx.value, "mp_iw",
        )
        offset = self._iadd(
            self._iadd(
                self._imul(c_ctx.value, height * width, "mp_coff"),
                in_h, "mp_hoff",
            ),
            iw, "mp_off",
        )
        xv = self._load(ty, self._gep(ty, x, offset, "mp_xp"), "mp_xv")
        mv = self._load(ty, max_ptr, "mp_mv")
        cmp_reg = self._fresh("mp_cmp")
        self._namer.register_definition(cmp_reg)
        self._p(f"  {cmp_reg} = fcmp ogt {ty} {xv}, {mv}")
        new_max = self._fresh("mp_new")
        self._namer.register_definition(new_max)
        self._p(f"  {new_max} = select i1 {cmp_reg}, {ty} {xv}, {ty} {mv}")
        self._p(f"  store {ty} {new_max}, {ty}* {max_ptr}")
        self._loop_close(kw_ctx)
        self._loop_close(kh_ctx)

        out_offset = self._iadd(
            self._iadd(
                self._imul(c_ctx.value, out_h * out_w, "mp_ooff0"),
                self._imul(h_ctx.value, out_w, "mp_ooff1"),
                "mp_ooff1",
            ),
            w_ctx.value, "mp_ooff",
        )
        result = self._load(ty, max_ptr, "mp_res")
        self._p(
            f"  store {ty} {result}, {ty}* "
            f"{self._gep(ty, out, out_offset, 'mp_op')}"
        )
        self._loop_close(w_ctx)
        self._loop_close(h_ctx)
        self._loop_close(c_ctx)
        self._finalize_from_buffer(instr, out, ty)

    def _emit_dot(self, instr: Instruction) -> None:
        """Dot product: sum(a[i] * b[i])."""
        ty = self._infer_type(instr)
        length = max(1, self._dim_of(
            instr, ("length", "len", "n"), 1, operand=0, axis=-1
        ))
        self._require_elements(instr, 0, length, "dot length")
        self._require_elements(instr, 1, length, "dot length")
        a = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(a, ty)
        b = self._ptr_of(instr, 1, ty)
        acc = self._alloc_slot(ty, 1, "dot_acc")
        self._p(f"  store {ty} 0.0, {ty}* {acc}")
        ctx = self._loop_open(length, None, "dot_i")
        av = self._load(ty, self._gep(ty, a, ctx.value, "dot_ap"), "dot_av")
        bv = self._load(ty, self._gep(ty, b, ctx.value, "dot_bp"), "dot_bv")
        prod = self._bin("fmul", ty, av, bv, "dot_pr")
        old = self._load(ty, acc, "dot_old")
        new_acc = self._bin("fadd", ty, old, prod, "dot_new")
        self._p(f"  store {ty} {new_acc}, {ty}* {acc}")
        self._loop_close(ctx)
        self._finalize_from_acc(instr, acc, ty)

    def _emit_matmul(self, instr: Instruction) -> None:
        """Matrix multiply: C[m,n] = A[m,k] x B[k,n] (row major)."""
        ty = self._infer_type(instr)
        m = self._dim_of(instr, ("m", "rows"), 1, operand=0, axis=0)
        k = self._dim_of(instr, ("k", "inner"), 1, operand=0, axis=1)
        n = self._dim_of(instr, ("n", "cols"), 1, operand=1, axis=1)
        m, k, n = max(1, m), max(1, k), max(1, n)
        self._require_elements(instr, 0, m * k, "matmul A")
        self._require_elements(instr, 1, k * n, "matmul B")
        a = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(a, ty)
        b = self._ptr_of(instr, 1, ty)
        c = self._dest_buffer(instr, m * n, ty)
        acc = self._alloc_slot(ty, 1, "mm_acc")

        i_ctx = self._loop_open(m, None, "mm_i")
        j_ctx = self._loop_open(n, None, "mm_j")
        self._p(f"  store {ty} 0.0, {ty}* {acc}")
        k_ctx = self._loop_open(k, None, "mm_k")
        a_off = self._iadd(
            self._imul(i_ctx.value, k, "mm_aoff0"), k_ctx.value, "mm_aoff"
        )
        av = self._load(ty, self._gep(ty, a, a_off, "mm_ap"), "mm_av")
        b_off = self._iadd(
            self._imul(k_ctx.value, n, "mm_boff0"), j_ctx.value, "mm_boff"
        )
        bv = self._load(ty, self._gep(ty, b, b_off, "mm_bp"), "mm_bv")
        prod = self._bin("fmul", ty, av, bv, "mm_pr")
        old = self._load(ty, acc, "mm_old")
        new_acc = self._bin("fadd", ty, old, prod, "mm_new")
        self._p(f"  store {ty} {new_acc}, {ty}* {acc}")
        self._loop_close(k_ctx)

        c_off = self._iadd(
            self._imul(i_ctx.value, n, "mm_coff0"), j_ctx.value, "mm_coff"
        )
        result = self._load(ty, acc, "mm_res")
        c_ptr = self._gep(ty, c, c_off, "mm_cp")
        self._p(f"  store {ty} {result}, {ty}* {c_ptr}")
        self._loop_close(j_ctx)
        self._loop_close(i_ctx)
        self._finalize_from_buffer(instr, c, ty)

    def _emit_gemm(self, instr: Instruction) -> None:
        """General matrix multiply: C = A x W (+ bias), optional trans_b."""
        ty = self._infer_type(instr)
        if instr.attrs.get("trans_a"):
            raise LLVMCodegenError("gemm trans_a is not supported")

        trans_b = bool(instr.attrs.get(
            "trans_b", instr.attrs.get("transB", False)
        ))
        m = self._dim_of(instr, ("M", "m", "rows"), 1, operand=0, axis=0)
        k = self._dim_of(instr, ("K", "k", "inner"), 1, operand=0, axis=1)
        if trans_b:
            n = self._dim_of(instr, ("N", "n", "cols"), 1, operand=1, axis=0)
        else:
            n = self._dim_of(instr, ("N", "n", "cols"), 1, operand=1, axis=1)
        m, k, n = max(1, m), max(1, k), max(1, n)
        self._require_elements(instr, 0, m * k, "gemm A")
        self._require_elements(instr, 1, k * n, "gemm W")
        if len(instr.operands) >= 3:
            self._require_elements(instr, 2, n, "gemm bias")
        a = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(a, ty)
        w = self._ptr_of(instr, 1, ty)
        bias = self._ptr_of(instr, 2, ty) if len(instr.operands) >= 3 else None
        c = self._dest_buffer(instr, m * n, ty)
        acc = self._alloc_slot(ty, 1, "gemm_acc")

        i_ctx = self._loop_open(m, None, "gemm_i")
        j_ctx = self._loop_open(n, None, "gemm_j")
        if bias is not None:
            bias_val = self._load(
                ty, self._gep(ty, bias, j_ctx.value, "gemm_bp"), "gemm_bias"
            )
        else:
            bias_val = _float_literal(0.0)
        self._p(f"  store {ty} {bias_val}, {ty}* {acc}")
        k_ctx = self._loop_open(k, None, "gemm_k")
        a_off = self._iadd(
            self._imul(i_ctx.value, k, "gemm_aoff0"), k_ctx.value, "gemm_aoff"
        )
        av = self._load(ty, self._gep(ty, a, a_off, "gemm_ap"), "gemm_av")
        if trans_b:
            w_off = self._iadd(
                self._imul(j_ctx.value, k, "gemm_woff0"),
                k_ctx.value, "gemm_woff",
            )
        else:
            w_off = self._iadd(
                self._imul(k_ctx.value, n, "gemm_woff0"),
                j_ctx.value, "gemm_woff",
            )
        wv = self._load(ty, self._gep(ty, w, w_off, "gemm_wp"), "gemm_wv")
        prod = self._bin("fmul", ty, av, wv, "gemm_pr")
        old = self._load(ty, acc, "gemm_old")
        new_acc = self._bin("fadd", ty, old, prod, "gemm_new")
        self._p(f"  store {ty} {new_acc}, {ty}* {acc}")
        self._loop_close(k_ctx)

        c_off = self._iadd(
            self._imul(i_ctx.value, n, "gemm_coff0"), j_ctx.value, "gemm_coff"
        )
        result = self._load(ty, acc, "gemm_res")
        c_ptr = self._gep(ty, c, c_off, "gemm_cp")
        self._p(f"  store {ty} {result}, {ty}* {c_ptr}")
        self._loop_close(j_ctx)
        self._loop_close(i_ctx)
        self._finalize_from_buffer(instr, c, ty)

    def _emit_conv(self, instr: Instruction) -> None:
        """2D convolution (NCHW layout) with stride/padding/bias."""
        ty = self._infer_type(instr)

        x_shape = tuple(instr.operands[0].shape)
        if len(x_shape) >= 3:
            x_cin, height, width = x_shape[-3], x_shape[-2], x_shape[-1]
        else:
            x_cin = height = width = 1
        w_shape = tuple(instr.operands[1].shape)
        if len(w_shape) >= 3:
            cout, cin, kernel = w_shape[0], w_shape[1], w_shape[2]
        else:
            cout = self._dim_of(instr, ("out_channels", "cout"), 1)
            kernel = self._dim_of(
                instr, ("kernel_size", "kernel_shape"), 3
            )
        x_cin = max(1, int(x_cin))
        height = max(1, int(height))
        width = max(1, int(width))
        cout = max(1, int(cout))
        cin = max(1, int(cin))
        kernel = max(1, int(kernel))
        self._require_elements(
            instr, 0, x_cin * height * width, "conv input"
        )
        self._require_elements(
            instr, 1, cout * cin * kernel * kernel, "conv weights"
        )
        if len(instr.operands) >= 3:
            self._require_elements(instr, 2, cout, "conv bias")
        x = self._ptr_of(instr, 0, ty)
        ty = self._ptr_elem_ty(x, ty)
        w = self._ptr_of(instr, 1, ty)
        bias = self._ptr_of(instr, 2, ty) if len(instr.operands) >= 3 else None

        stride = max(1, self._dim_of(instr, ("stride", "strides"), 1))
        padding = max(0, self._as_int(
            instr.attrs.get("padding", instr.attrs.get("pads", 0)), 0
        ))
        out_h = max(0, (height + 2 * padding - kernel) // stride + 1)
        out_w = max(0, (width + 2 * padding - kernel) // stride + 1)
        out = self._dest_buffer(instr, cout * out_h * out_w, ty)
        acc = self._alloc_slot(ty, 1, "conv_acc")

        oc_ctx = self._loop_open(cout, None, "conv_oc")
        out_oc = self._imul(oc_ctx.value, out_h * out_w, "conv_out_oc")
        w_oc = self._imul(oc_ctx.value, cin * kernel * kernel, "conv_w_oc")

        oh_ctx = self._loop_open(out_h, None, "conv_oh")
        oh_s = self._imul(oh_ctx.value, stride, "conv_ohS")
        ow_ctx = self._loop_open(out_w, None, "conv_ow")
        ow_s = self._imul(ow_ctx.value, stride, "conv_owS")
        if bias is not None:
            bias_val = self._load(
                ty, self._gep(ty, bias, oc_ctx.value, "conv_bp"), "conv_bias"
            )
        else:
            bias_val = _float_literal(0.0)
        self._p(f"  store {ty} {bias_val}, {ty}* {acc}")

        ic_ctx = self._loop_open(cin, None, "conv_ic")
        in_ic = self._imul(ic_ctx.value, height * width, "conv_in_ic")
        w_ic = self._imul(ic_ctx.value, kernel * kernel, "conv_w_ic")

        kh_ctx = self._loop_open(kernel, None, "conv_kh")
        ih = self._iadd(oh_s, kh_ctx.value, "conv_ih0")
        if padding:
            ih = self._isub(ih, padding, "conv_ih")
        ok_h_lo = self._icmp("sge", ih, 0, "conv_okh_lo")
        ok_h_hi = self._icmp("slt", ih, height, "conv_okh_hi")
        ok_h = self._bin_i1("and", ok_h_lo, ok_h_hi, "conv_okh")
        in_h = self._imul(ih, width, "conv_in_h")
        w_kh = self._imul(kh_ctx.value, kernel, "conv_w_kh")

        kw_ctx = self._loop_open(kernel, None, "conv_kw")
        iw = self._iadd(ow_s, kw_ctx.value, "conv_iw0")
        if padding:
            iw = self._isub(iw, padding, "conv_iw")
        ok_w_lo = self._icmp("sge", iw, 0, "conv_okw_lo")
        ok_w_hi = self._icmp("slt", iw, width, "conv_okw_hi")
        ok_w = self._bin_i1("and", ok_w_lo, ok_w_hi, "conv_okw")
        ok = self._bin_i1("and", ok_h, ok_w, "conv_ok")
        mac_label = self._fresh_label("conv_mac")
        skip_label = self._fresh_label("conv_skip")
        self._terminate(
            f"br i1 {ok}, label %{mac_label}, label %{skip_label}"
        )
        self._start_block(mac_label)
        x_off = self._iadd(
            self._iadd(in_ic, in_h, "conv_xoff0"), iw, "conv_xoff"
        )
        xv = self._load(ty, self._gep(ty, x, x_off, "conv_xp"), "conv_xv")
        w_off = self._iadd(
            self._iadd(w_oc, w_ic, "conv_woff0"),
            self._iadd(w_kh, kw_ctx.value, "conv_woff1"),
            "conv_woff",
        )
        wv = self._load(ty, self._gep(ty, w, w_off, "conv_wp"), "conv_wv")
        prod = self._bin("fmul", ty, xv, wv, "conv_pr")
        old = self._load(ty, acc, "conv_acc_v")
        new_acc = self._bin("fadd", ty, old, prod, "conv_acc_n")
        self._p(f"  store {ty} {new_acc}, {ty}* {acc}")
        self._start_block(skip_label)
        self._loop_close(kw_ctx)
        self._loop_close(kh_ctx)
        self._loop_close(ic_ctx)

        out_off = self._iadd(
            self._iadd(
                out_oc, self._imul(oh_ctx.value, out_w, "conv_oh_off"),
                "conv_ooff0",
            ),
            ow_ctx.value, "conv_ooff",
        )
        result = self._load(ty, acc, "conv_res")
        out_ptr = self._gep(ty, out, out_off, "conv_op")
        self._p(f"  store {ty} {result}, {ty}* {out_ptr}")
        self._loop_close(ow_ctx)
        self._loop_close(oh_ctx)
        self._loop_close(oc_ctx)
        self._finalize_from_buffer(instr, out, ty)

    def _emit_reshape(self, instr: Instruction) -> None:
        """Reshape is a pointer/register alias; no instruction is emitted."""
        if instr.dest is None:
            return
        if not instr.operands:
            raise LLVMCodegenError("reshape without operand")
        val = instr.operands[0]
        ref = self._value_ref(val)
        ty = self._ref_types.get(ref)
        if ty is None:
            ty = self._value_type(val)
        self._bind_dest(instr, ref, ty)


# Module-level helpers --------------------------------------------------------


def _llvm_type(dtype: DataType) -> str:
    return _TYPE_MAP.get(dtype, "float")


def _llvm_const(val: Value) -> str:
    """Format an IR Value as an LLVM constant."""
    if val.const_value is not None:
        cv = val.const_value
        return _llvm_const_val(cv, _llvm_type(val.dtype))
    return "0.0"


def _float_to_llvm_hex(value: float) -> str:
    """Encode a Python float as an LLVM double-precision hex literal.

    The value is first rounded to float32 so it is exactly representable
    in either ``float`` or ``double`` IR types.
    """
    f32 = struct.unpack("<f", struct.pack("<f", value))[0]
    bits = struct.unpack("<Q", struct.pack("<d", float(f32)))[0]
    return f"0x{bits:016X}"


def _float_literal(value: float) -> str:
    """Short form for 0.0/1.0/-1.0, hex otherwise (LLVM 10 strict rules)."""
    if value == 0.0:
        return "0.0"
    if value == 1.0:
        return "1.0"
    if value == -1.0:
        return "-1.0"
    return _float_to_llvm_hex(value)


def _llvm_const_val(value: float | int, ty: str) -> str:
    if ty in _FLOAT_TYPES:
        return _float_literal(float(value))
    return str(int(value))
